import { ENVIRONMENT } from '@env';

export const AdapterConfigure = {
  SCHEMA: ENVIRONMENT.API_KEY.SCHEMA,
  ENTITY: ENVIRONMENT.API_KEY.ENTITY,
  ROUTE: ENVIRONMENT.API_KEY.ROUTE,

  ENDPOINT: {
    LIST: ENVIRONMENT.API_KEY.ROUTE,
    CREATE: ENVIRONMENT.API_KEY.ROUTE,
    REVOKE: (id: number) => `${ENVIRONMENT.API_KEY.ROUTE}/${id}`,
  },
};
