import { ENVIRONMENT } from '@env';

export const AdapterConfigure = {
  SCHEMA: ENVIRONMENT.WEBHOOK.SCHEMA,
  ENTITY: ENVIRONMENT.WEBHOOK.ENTITY,
  ROUTE: ENVIRONMENT.WEBHOOK.ROUTE,

  ENDPOINT: {
    LIST: ENVIRONMENT.WEBHOOK.ROUTE,
    CREATE: ENVIRONMENT.WEBHOOK.ROUTE,
    UPDATE: (id: number) => `${ENVIRONMENT.WEBHOOK.ROUTE}/${id}`,
    REMOVE: (id: number) => `${ENVIRONMENT.WEBHOOK.ROUTE}/${id}`,
  },
};
